### ISSUE TITLE
调用火山方舟模型，程序会崩溃

### ISSUE THREAD

**Issue by BlueHtml** [fruitbars/simple-one-api#45]
你好，我是按照[火山方舟大模型接入指南](https://github.com/fruitbars/simple-one-api/blob/main/docs/%E7%81%AB%E5%B1%B1%E6%96%B9%E8%88%9F%E5%A4%A7%E6%A8%A1%E5%9E%8B%E6%8E%A5%E5%85%A5%E6%8C%87%E5%8D%97.md)配置的。然后使用自带的webui，一调用这个模型`ep-20240728142023-999rx`，程序就会崩溃。

在火山后台测试调用没有问题，抓包看到接口也正常返回数据了，但是咱们程序一调用就崩溃。

崩溃日志如下：
```
2024-07-28T15:30:42.477+0800    INFO    mywebui/multi_model_call.go:82  Received message from client    {"message": "{\"prompt\":\"你好，大模型\",\"temperature\":0.5,\"maxTokens\":4096,\"topP\":0,\"models\":[\"ep-20240728142023-999rx\"],\"system\":\"\"}"}
2024-07-28T15:30:42.480+0800    INFO    mywebui/multi_model_call.go:88  Received models {"models": ["ep-20240728142023-999rx"]}
[GIN-debug] [WARNING] Running in "debug" mode. Switch to "release" mode in production.
 - using env:   export GIN_MODE=release
 - using code:  gin.SetMode(gin.ReleaseMode)

[GIN-debug] POST   /v1/chat/completions      --> simple-one-api/pkg/simple_client.(*SimpleClient).CreateChatCompletionStream.func2 (2 handlers)
2024-07-28T15:30:42.481+0800    INFO    handler/openai_handler.go:146   Service details {"service_name": "huoshan", "client_model": "ep-20240728142023-999rx", "g_redirect_model": "ep-20240728142023-999rx", "service_model_name": "ep-20240728142023-999rx", "redirect_model": "ep-20240728142023-999rx", "map_model": "ep-20240728142023-999rx", "last_model": "ep-20240728142023-999rx"}
2024-07-28T15:30:42.924+0800    INFO    mywebui/multi_model_call.go:134 Stream finished
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x18 pc=0x1748f7e]

goroutine 10 [running]:
simple-one-api/pkg/simple_client.(*CustomResponseWriter).CloseNotify(0xc00007c7b8?)
        <autogenerated>:1 +0x1e
github.com/gin-gonic/gin.(*Context).Stream(0xc000481f80?, 0xc00034aff0)
        /Users/admin/go/pkg/mod/github.com/gin-gonic/gin@v1.10.0/context.go:1118 +0x2f
simple-one-api/pkg/handler.handleHuoShanStream({0x1c0c9a0, 0x25d8900}, _, _, {{0xc000481f80, 0x17}, {0xc00007c7b0, 0x1, 0x1}, 0x0, ...})
        /Users/admin/GolandProjects/myopengoprjs/simple-one-api/pkg/handler/openai_huoshan_handler.go:108 +0x185
simple-one-api/pkg/handler.OpenAI2HuoShanHandler(0xc0001a1100, 0xc0005592f0?)
        /Users/admin/GolandProjects/myopengoprjs/simple-one-api/pkg/handler/openai_huoshan_handler.go:76 +0x2f1
simple-one-api/pkg/handler.dispatchToServiceHandler(0xc0001a1100, 0xc0003be7e0)
        /Users/admin/GolandProjects/myopengoprjs/simple-one-api/pkg/handler/openai_handler.go:273 +0x64
simple-one-api/pkg/handler.HandleOpenAIRequest(0xc0001a1100, 0xc0001a0f00)
        /Users/admin/GolandProjects/myopengoprjs/simple-one-api/pkg/handler/openai_handler.go:257 +0x1fa5
simple-one-api/pkg/simple_client.(*SimpleClient).CreateChatCompletionStream.func2(0xd8a505?)
        /Users/admin/GolandProjects/myopengoprjs/simple-one-api/pkg/simple_client/simple_client.go:86 +0x17
github.com/gin-gonic/gin.(*Context).Next(...)
        /Users/admin/go/pkg/mod/github.com/gin-gonic/gin@v1.10.0/context.go:185
simple-one-api/pkg/simple_client.(*SimpleClient).CreateChatCompletionStream.func1(0xc0001a1100)
        /Users/admin/GolandProjects/myopengoprjs/simple-one-api/pkg/simple_client/simple_client.go:83 +0x107
github.com/gin-gonic/gin.(*Context).Next(...)
        /Users/admin/go/pkg/mod/github.com/gin-gonic/gin@v1.10.0/context.go:185
github.com/gin-gonic/gin.(*Engine).handleHTTPRequest(0xc00033a000, 0xc0001a1100)
        /Users/admin/go/pkg/mod/github.com/gin-gonic/gin@v1.10.0/gin.go:633 +0x892
github.com/gin-gonic/gin.(*Engine).ServeHTTP(0xc00033a000, {0x1c0b720, 0xc0001efb80}, 0xc00057cd80)
        /Users/admin/go/pkg/mod/github.com/gin-gonic/gin@v1.10.0/gin.go:589 +0x1b2
simple-one-api/pkg/simple_client.(*SimpleClient).CreateChatCompletionStream.func3()
        /Users/admin/GolandProjects/myopengoprjs/simple-one-api/pkg/simple_client/simple_client.go:95 +0x1e7
created by simple-one-api/pkg/simple_client.(*SimpleClient).CreateChatCompletionStream in goroutine 9
        /Users/admin/GolandProjects/myopengoprjs/simple-one-api/pkg/simple_client/simple_client.go:90 +0x315
```

**Comment by fruitbars** [comment]
收到，我看能否重现修复该问题。

**Comment by fruitbars** [comment]
已修复，试试v0.9.3， https://github.com/fruitbars/simple-one-api/releases/tag/v0.9.3

**Comment by BlueHtml** [comment]
@fruitbars 谢谢，现在正常了。
不过我看现在配置是有变动的，希望大佬有空可以同步更新下最新的配置文档

**Comment by fruitbars** [comment]
原来的配置兼容的。新加了一些新配置项，比如api_keys，可以配置多个客户端的api_key

飞书上会实时更新哈：
https://rsxlecz746.feishu.cn/wiki/Tr8nwkkvii3DJrkCpjQcmReAndV?fromScene=spaceOverview

**Comment by BlueHtml** [comment]
> 原来的配置兼容的。新加了一些新配置项，比如api_keys，可以配置多个客户端的api_key
> 
> 飞书上会实时更新哈： https://rsxlecz746.feishu.cn/wiki/Tr8nwkkvii3DJrkCpjQcmReAndV?fromScene=spaceOverview

收到，我去看看
